{% set name = "networkx" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de346335408f84de0eada6ff9fafafff9bcda11f0a0dfaa931133debb146ab61
build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
  run-constrained:
    - numpy >=1.20
    - scipy >=1.8
    - matplotlib >=3.4
    - pandas >=1.3
    - lxml >=4.6
    - pygraphviz >=1.10
    - pydot >=1.4.2
    - sympy >=1.10

test:
  imports:
    - networkx
    - networkx.algorithms
    - networkx.algorithms.approximation
    - networkx.algorithms.assortativity
    - networkx.algorithms.bipartite
    - networkx.algorithms.centrality
    - networkx.algorithms.coloring
    - networkx.algorithms.community
    - networkx.algorithms.components
    - networkx.algorithms.connectivity
    - networkx.algorithms.flow
    - networkx.algorithms.isomorphism
    - networkx.algorithms.link_analysis
    - networkx.algorithms.minors
    - networkx.algorithms.operators
    - networkx.algorithms.shortest_paths
    - networkx.algorithms.traversal
    - networkx.algorithms.tree
    - networkx.classes
    - networkx.drawing
    - networkx.generators
    - networkx.linalg
    - networkx.readwrite
    - networkx.readwrite.json_graph
    - networkx.tests
    - networkx.utils
  requires:
    - pip
  commands:
    - pip check
  #downstreams:
  #  - pythran
  #  - scikit-image
  #  - pomegranate

about:
  home: https://networkx.github.io/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Python package for creating and manipulating complex networks
  description: |
    NetworkX is a Python language software package for the creation,
    manipulation, and study of the structure, dynamics, and functions of complex
    networks.
  doc_url: https://networkx.org/documentation/stable
  dev_url: https://github.com/networkx/networkx

extra:
  skip-lints:
    - invalid_url   # it is common URL ...
  recipe-maintainers:
    - synapticarbors
    - ocefpaf
    - SylvainCorlay
    - FelixMoelder
