{% set version = "2.6.2" %}

package:
  name: networkx
  # Versions 2.6, 2.6.1 have been yanked https://pypi.org/project/networkx/#history
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/networkx/networkx-{{ version }}.tar.gz
  sha256: 2306f1950ce772c5a59a57f5486d59bb9cab98497c45fc49cbc45ac0dec119bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    # 2021/7/28: Optional dependencies numpy, scipy, matplotlib, pandas,
    # but they can cause issues when try to build scipy or pythran,
    # see https://github.com/networkx/networkx/commit/5b86d913117ee22d9522755d607b5c6256cd57b9
    #- numpy >=1.19
    #- scipy >=1.5,!=1.6.1
    #- matplotlib >=3.3
    #- pandas >=1.1
    # Optional lxml, pygraphviz, pydot, gdal packages provide additional functionality

test:
  imports:
    - networkx
    - networkx.algorithms
    - networkx.algorithms.approximation
    - networkx.algorithms.assortativity
    - networkx.algorithms.bipartite
    - networkx.algorithms.centrality
    - networkx.algorithms.coloring
    - networkx.algorithms.community
    - networkx.algorithms.components
    - networkx.algorithms.connectivity
    - networkx.algorithms.flow
    - networkx.algorithms.isomorphism
    - networkx.algorithms.link_analysis
    - networkx.algorithms.minors
    - networkx.algorithms.node_classification
    - networkx.algorithms.operators
    - networkx.algorithms.shortest_paths
    - networkx.algorithms.traversal
    - networkx.algorithms.tree
    - networkx.classes
    - networkx.drawing
    - networkx.generators
    - networkx.linalg
    - networkx.readwrite
    - networkx.readwrite.json_graph
    - networkx.tests
    - networkx.testing
    - networkx.utils
  sourse_files:
    - tests/
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://networkx.github.io/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Python package for creating and manipulating complex networks
  description: |
    NetworkX is a Python language software package for the creation,
    manipulation, and study of the structure, dynamics, and functions of complex
    networks.
  doc_url: http://networkx.github.io/documentation.html
  dev_url: https://github.com/networkx/networkx
  doc_source_url: https://github.com/networkx/networkx/blob/v1.11/doc/source/index.rst

extra:
  recipe-maintainers:
    - synapticarbors
    - ocefpaf
    - SylvainCorlay
    - FelixMoelder
