travis:
  secure:
    BINSTAR_TOKEN: QKeyjH2jNQt3C2DPx97yPQX6STQYaiGXtV/wNY2Jo1AV9YIApx2Pl1cwLNf2iswsNK5csOpxImhmZaE/qqqor3Z/njOLMpSnHTgtlfaOV1BovIXL4vKgC9M3/4Biswp4NOSAFvbz2ceZogEqgXzVEc6uwfHwqCeSwwelbYbmDszJEu7VJ4TsKUVnyb+q7hlaP9UEECKC7DW3ibi+8hrXmnq1bMOJxy5ZVUnkYhdHT/ICmo2o4+w6oARhm00yuhuChb103G1TXD7OtaIiuk/q5gFBPm0V5AAbq2HCwG4JFnERNKFf0Bf9Q3ZagLPDthDepIV69b52llMCmtYLdTGKhQO71hv227UAWoUCFMqll99zfjVh7rgIUbx+g9dGHV/sBJbASEr6o0qXx4N3z1uXdA3GsZ4DAlvAREFJXHgIwAm5iz49w9l/bSwPsLDWVC3peBFOzEXzDP/lZJrXIqgUynNHoXxqSShRBWXkYBYvDvtXcRsWK9Gnlb7onvwa/+jGiFxe7BykRUQotxSUVVYaLOPjIUWXVLzNFfe9nrsUIZ8alP36uIWsQdAxNUzcwLv/7iVnx3QVP0SR7Zu4B0EddISDFKtnZDmF5L3nHNoRDMc2dhk3zVHogzVI6zzspbkrb2kcS4kAGMHXy2FI2leSDRTzg0SSpClqw7sIF6C/AhU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
