travis:
  secure:
    BINSTAR_TOKEN: FPnptxf0E7oQHEUmnB15WxnYze6hqXw1J4JQ24qAMjZOjm6WIcIIghsMu6VPoM92OoeFtpDRh+vI7Xvk4MIIq4Yi817U7Bz9H+PWQ9/2yIsQNizLaHefj2wo+PXSzqkORMxIEb1j/krB/FLxMPvDLYyTXH20xmOmZ+UwyYP6JVZRV6XXr1tVzfZQRyBpvuSbYtZLpGwdtavH+l+Gp3oiCyCCKxbv0NdeXUpDkDofGCT/AMbcXlB1MYI7uUW7sYfQWc0n5GEVuyTvzuXtqX5vYIut1jYoSZb4snTPqje8hyljUUbcelSAq4cEnDwuulMYgkALc/B++JmHq969NtaJvXbL39CWUSPIH7AgCpfOzGB8CBxQ8yT+oceKATYG+/iFJvzlQzyL7duvwHsAlSn80j6Ml0q1s56iuUIi8Z7JdWF/7cRMu2d5hFWy9EaFMEVKRoeKtJLP+YWZZ8kUm6AHJjQNMYbw7zKRAE8nZ0CE5HaSf7qslS2ZofrUt3sr+uYqReW77CH9Qy29WiW01OK1jBrykqqYWrxW8tJwQVydoY5tEcQUQYeIeCh7y1IRVvxPkhkM4e2zO5MVrmhU1ek5+CUxf0PA/aN2T2PissaYS9N1tklB8cZh+lOFwrjT/YaHdxHy1Vd8WW/HsZYGYozIEwZCmb9Us+n6ia/gzsBzU/A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
