travis:
  secure:
    BINSTAR_TOKEN: W8UYK/gzH+t7Fkq4uiPf0utrgIUVab/X68Sc7eLH7VsmPm0nmgDK7hsruJ/WGB9dv2yAeFYuIHCt5dgBsdm9WmOwAEUghDmq2dZa5mFXX0jUzZthmweO08OptCxMcu0S466Spu9DnS7UuQ+571VCj1O+nlf7tgEvkbvL15kBx7fMg7p7i7bSTMQXv9NC0cVSM+q3y580jkmPCmxty9tfXS+6G/XwsIm1UHst6N0WvVws9QtbKTZwfafQ5FivEd4FP3czJoxwAweMGYk2smJew8j3ZPrA9vy6gcj/acEFd7H0u4m2mRWvVi9FguDkCvSmMxDs//FNqFuvyZ1q6U7iod4s3jBdOXT+7okrb9WTPaY9iUhcVGmz9agHFooc7Y1Orj1OKAIVL+qsAHXIaoPiNwMcJj6Cf4Ik2SJasQwo1yTpcozuAkpZbBM0yKPzYw0c2eyDwQ+9Nk+AOGmtacLyu8pKGNojx3TPCURCeLtNbwiVeXg3y9Z5ALzUqjZRRE8KSn1AqaBelLMfkeady2dElR74SiVu28E9uZXAEoemywBkBM7G/srI3eCude0BxKisuoVm36YUbrwGQ4Ldz1awokctkBC/fjb1Kktcm6TVxrIemGnDS3/vxNUF2ZqjEZTZQ4xWEEpJIiJUU2LzBt9ZK7kV77diQ+LSY1KNXUTWXq4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
